/**
 * @file    blinky_two_leds.c
 * @brief   Example: Two LED blinky using Lelu Scheduler
 * 
 * @details This example demonstrates the Lelu Scheduler by blinking two LEDs
 *          at different rates:
 *          - LED1 (PA5): Fast blink at 250ms (2 Hz)
 *          - LED2 (PA6): Slow blink at 1000ms (0.5 Hz)
 * 
 *          Debug output is shown via UART. For USB CDC, see the CDC
 *          print callback example in the README.
 * 
 * @note    This is example code - adapt GPIO pins and print callback for your board.
 */

#include "main.h"
#include "../include/lelu_scheduler.h"
#include <string.h>
#include <stdio.h>

/* ============== Hardware Handles ============== */

UART_HandleTypeDef huart2;  /* For debug output */

/* ============== Debug Print Callback ============== */

/**
 * @brief  Print callback for scheduler debug output via UART.
 *         Replace this with a CDC or other implementation for your board.
 * @param  msg  Null-terminated string to transmit
 */
void scheduler_uart_print(const char* msg)
{
    HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), 100);
}

/* ============== Task Functions ============== */

/**
 * @brief Task: Blink LED1 (fast - every 250ms)
 */
void task_blink_led1(void)
{
    HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
}

/**
 * @brief Task: Blink LED2 (slow - every 1000ms)
 */
void task_blink_led2(void)
{
    HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_6);
}

/* ============== HAL Tick Override ============== */

/**
 * @brief Override HAL_IncTick to include scheduler timing.
 *        Called every 1ms by the SysTick interrupt.
 */
void HAL_IncTick(void)
{
    uwTick += (uint32_t)uwTickFreq;
    lelu_scheduler_systick();
}

/* ============== Main Function ============== */

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();

    /* Initialize scheduler with UART debug output.
     * Pass NULL instead to disable debug, or use a CDC callback. */
    lelu_scheduler_init(scheduler_uart_print);

    /* Register tasks */
    lelu_scheduler_add_task("LED1_fast", task_blink_led1, 250,  NULL);
    lelu_scheduler_add_task("LED2_slow", task_blink_led2, 1000, NULL);

    lelu_scheduler_set_boot_done();

    /* Main loop */
    uint32_t loop_count = 0;

    while (1)
    {
        lelu_scheduler_run();

        loop_count++;
        if (loop_count % 400 == 0)
        {
            lelu_scheduler_print_stats();
        }

        while (!lelu_scheduler_tick_pending())
        {
            __WFI();
        }
        lelu_scheduler_clear_tick();
    }
}

/* ============== Placeholder Functions ============== */
/* 
 * These functions are board-specific and must be implemented by the user.
 * They are typically generated by STM32CubeMX.
 */

/*
void SystemClock_Config(void) { ... }
void MX_GPIO_Init(void) { ... }
void MX_USART2_UART_Init(void) { ... }
*/
