/**
 * @file    blinky_two_leds.c
 * @brief   Example: Two LED blinky using Lelu Scheduler
 * 
 * @details This example demonstrates the Lelu Scheduler by blinking two LEDs
 *          at different rates:
 *          - LED1 (PA5): Fast blink at 250ms (2 Hz)
 *          - LED2 (PA6): Slow blink at 1000ms (0.5 Hz)
 * 
 * @note    This is example code - adapt GPIO pins and UART for your board.
 */

#include "main.h"
#include "../include/lelu_scheduler.h"
#include <string.h>
#include <stdio.h>

/* ============== Hardware Handles ============== */

UART_HandleTypeDef huart2;  /* For debug output */

/* ============== Task Functions ============== */

/**
 * @brief Task: Blink LED1 (fast - every 250ms)
 * 
 * This task toggles LED1, creating a 2 Hz blink pattern (500ms full cycle).
 */
void task_blink_led1(void)
{
    HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
}

/**
 * @brief Task: Blink LED2 (slow - every 1000ms)
 * 
 * This task toggles LED2, creating a 0.5 Hz blink pattern (2 second full cycle).
 */
void task_blink_led2(void)
{
    HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_6);
}

/* ============== HAL Tick Override ============== */

/**
 * @brief Override HAL_IncTick to include scheduler timing
 * 
 * This function is called every 1ms by the SysTick interrupt.
 * We add the scheduler's systick call here to keep time.
 */
void HAL_IncTick(void)
{
    uwTick += (uint32_t)uwTickFreq;
    lelu_scheduler_systick();  /* Feed the scheduler */
}

/* ============== Main Function ============== */

/**
 * @brief Main function - initializes system and runs scheduler
 */
int main(void)
{
    /* ========== MCU Initialization ========== */
    HAL_Init();
    SystemClock_Config();     /* Configure system clock (user-defined) */
    MX_GPIO_Init();           /* Initialize GPIOs (user-defined) */
    MX_USART2_UART_Init();    /* Initialize UART for debug (user-defined) */
    
    /* ========== Initialize Scheduler ========== */
    /* Pass UART handle for debug messages, or NULL to disable debug output */
    lelu_scheduler_init(&huart2);
    
    /* ========== Register Tasks ========== */
    uint8_t led1_task_id;
    uint8_t led2_task_id;
    
    /* Task 1: Fast LED blink (250ms interval = 4 toggles/second = 2 Hz blink) */
    lelu_scheduler_add_task("LED1_fast",    /* Task name (for debug) */
                            task_blink_led1, /* Function to call */
                            250,             /* Period in milliseconds */
                            &led1_task_id);  /* Receives task ID */
    
    /* Task 2: Slow LED blink (1000ms interval = 1 toggle/second = 0.5 Hz blink) */
    lelu_scheduler_add_task("LED2_slow", 
                            task_blink_led2, 
                            1000, 
                            &led2_task_id);
    
    /* ========== Mark Boot Complete ========== */
    /* This enables overrun detection - call after all setup is done */
    lelu_scheduler_set_boot_done();
    
    /* ========== Main Loop ========== */
    uint32_t loop_count = 0;
    
    while (1)
    {
        /* Run the scheduler - checks all tasks and executes ready ones */
        lelu_scheduler_run();
        
        /* Optional: Print statistics every ~10 seconds */
        loop_count++;
        if (loop_count % 400 == 0)  /* 400 iterations * 25ms tick = 10 seconds */
        {
            lelu_scheduler_print_stats();
        }
        
        /* Wait for next scheduler tick (saves power) */
        while (!lelu_scheduler_tick_pending())
        {
            /* Enter low-power mode while waiting */
            __WFI();  /* Wait For Interrupt - ARM instruction */
        }
        
        /* Clear the tick flag to acknowledge we processed it */
        lelu_scheduler_clear_tick();
    }
}

/* ============== Placeholder Functions ============== */
/* 
 * These functions are board-specific and must be implemented by the user.
 * They are included here as placeholders to show what's needed.
 */

/*
void SystemClock_Config(void)
{
    // Configure system clock for your MCU
    // Generated by STM32CubeMX
}

void MX_GPIO_Init(void)
{
    // Enable GPIO clocks
    __HAL_RCC_GPIOA_CLK_ENABLE();
    
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    
    // Configure LED1 (PA5) and LED2 (PA6) as outputs
    GPIO_InitStruct.Pin = GPIO_PIN_5 | GPIO_PIN_6;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
}

void MX_USART2_UART_Init(void)
{
    // Configure UART for debug output
    // Generated by STM32CubeMX
}
*/
